### ISSUE TITLE
Inconsistent snake_case vs camelCase for Response keys

### ISSUE THREAD

**Issue by BryanBaird** [civisanalytics/civis-python#317] opened 2019-08-15 20:34 UTC
I am working on a script that involves pulling the completion time for the last run of a preceding import job.

From other examples and documentation, I could find that the information I was looking for would be retrievable by `client.jobs.get(IMPORT_JOB_ID).last_run`. However, in [the documentation](https://civis-python.readthedocs.io/en/stable/api_resources.html?highlight=last_run#jobs), the key for the field in question is `finished_at`. The returned dict instead has `finishedAt` in camel case, and similarly `createdAt` and `startedAt`. It wasn't too hard to troubleshoot once I could inspect the outputs manually, but it did break my code on the first couple of runs.

**Comment by jacksonlee-civis** [comment] 2021-11-15 22:49
Confirmed that I was able to reproduce the described behavior with `client.jobs.get(...)`. More generally, not just for the Jobs endpoint, this observation holds true for a nested `Response` object's attributes/keys (the `Response` class subclasses the built-in `dict`). This is a bug, or at least an intentional feature that's turned out to be very confusing and unintuitive to the user (I've just tracked down some old internal documentation for _when_ this behavior was intentionally introduced in an internal project, though not for _why_).

A natural way to resolve this "bug" would be to keep a consistent behavior for snake_cake versus camelCase. Currently, as of v1.15.1, the default behavior consistently has `APIClient` set `return_type` to `"snake"` and `Response` set `snake_case` to `True`, which should strongly suggest to the user that _all_ keys/attributes of a `Response` object, nested or not, should be in snake_case by default -- indeed that's what the documentation website shows, as Bryan reported.

Resolving this issue in this way would result in a breaking change, since many users have already written code for this default, non-intuitive behavior of "snake_case for a top-level key, but camelCase for a nested key". For this reason, I've attached this issue to the "v2.0.0" milestone.

The code changes that are likely needed --

Change the following current code:

https://github.com/civisanalytics/civis-python/blob/9a8d18df9ef5a1b4ae5b4c3e96a16b4f5f5c4b6c/civis/response.py#L135-L139

into something like this:

```python
                if isinstance(v, dict):
                    val = Response(v, snake_case=snake_case)
                elif isinstance(v, list):
                    val = [Response(o, snake_case=snake_case) if isinstance(o, dict) else o
                           for o in v]
```

Also, remove this docstring line:

https://github.com/civisanalytics/civis-python/blob/9a8d18df9ef5a1b4ae5b4c3e96a16b4f5f5c4b6c/civis/response.py#L117

FWIW, #228 is another issue for which the `Response` class may need a breaking change for v2.0.0.

**Closed** 2023-03-14 14:33 UTC
Labels: bug, Documentation
